module.exports.stations = [
	'Acton Town Station',
	'Aldgate Station',
	'Aldgate East Station',
	'Alperton Station',
	'Amersham Station',
	'Angel Station',
	'Archway Station',
	'Arnos Grove Station',
	'Arsenal Station',
	'Baker Street Station',
	'Balham Station',
	'Bank Station',
	'Barbican Station',
	'Barking Station',
	'Barkingside Station',
	'Barons Court Station',
	'Bayswater Station',
	'Becontree Station',
	'Belsize Park Station',
	'Bermondsey Station',
	'Bethnal Green Station',
	'Blackfriars Station',
	'Blackhorse Road Station',
	'Bond Street Station',
	'Borough Station',
	'Boston Manor Station',
	'Bounds Green Station',
	'Bow Road Station',
	'Brent Cross Station',
	'Brixton Station',
	'Buckhurst Hill Station',
	'Burnt Oak Station',
	'Caledonian Road Station',
	'Camden Town Station',
	'Canada Water Station',
	'Canary Wharf Station',
	'Canning Town Station',
	'Cannon Street Station',
	'Canons Park Station',
	'Chalfont & Latimer Station',
	'Chalk Farm Station',
	'Chancery Lane Station',
	'Charing Cross Station',
	'Chesham Station',
	'Chigwell Station',
	'Chiswick Park Station',
	'Chorleywood Station',
	'Clapham Common Station',
	'Clapham North Station',
	'Clapham South Station',
	'Cockfosters Station',
	'Colindale Station',
	'Colliers Wood Station',
	'Covent Garden Station',
	'Croxley Station',
	'Dagenham East Station',
	'Dagenham Heathway Station',
	'Debden Station',
	'Dollis Hill Station',
	'Ealing Broadway Station',
	'Ealing Common Station',
	"Earl's Court Station",
	'East Acton Station',
	'East Finchley Station',
	'East Ham Station',
	'East Putney Station',
	'Eastcote Station',
	'Edgware Station',
	'Elephant & Castle Station',
	'Elm Park Station',
	'Embankment Station',
	'Epping Station',
	'Euston Station',
	'Euston Square Station',
	'Fairlop Station',
	'Farringdon Station',
	'Finchley Central Station',
	'Finchley Road Station',
	'Finsbury Park Station',
	'Fulham Broadway Station',
	'Gants Hill Station',
	'Gloucester Road Station',
	'Golders Green Station',
	'Goldhawk Road Station',
	'Goodge Street Station',
	'Grange Hill Station',
	'Great Portland Street Station',
	'Green Park Station',
	'Greenford Station',
	'Hainault Station',
	'Hampstead Station',
	'Hanger Lane Station',
	'Hatton Cross Station',
	'Heathrow Terminal 4 Station',
	'Hendon Central Station',
	'High Barnet Station',
	'High Street Kensington Station',
	'Highbury & Islington Station',
	'Highgate Station',
	'Hillingdon Station',
	'Holborn Station',
	'Holland Park Station',
	'Holloway Road Station',
	'Hornchurch Station',
	'Hounslow Central Station',
	'Hounslow East Station',
	'Hounslow West Station',
	'Hyde Park Corner Station',
	'Ickenham Station',
	'Kennington Station',
	'Kentish Town Station',
	'Kilburn Station',
	'Kilburn Park Station',
	'Kingsbury Station',
	'Knightsbridge Station',
	'Ladbroke Grove Station',
	'Lambeth North Station',
	'Lancaster Gate Station',
	'Latimer Road Station',
	'Leicester Square Station',
	'Leyton Station',
	'Leytonstone Station',
	'Liverpool Street Station',
	'London Bridge Station',
	'Loughton Station',
	'Maida Vale Station',
	'Manor House Station',
	'Mansion House Station',
	'Marble Arch Station',
	'Marylebone Station',
	'Mile End Station',
	'Mill Hill East Station',
	'Monument Station',
	'Moor Park Station',
	'Moorgate Station',
	'Morden Station',
	'Mornington Crescent Station',
	'Neasden Station',
	'Newbury Park Station',
	'North Acton Station',
	'North Ealing Station',
	'North Greenwich Station',
	'North Harrow Station',
	'Northfields Station',
	'Northolt Station',
	'Northwick Park Station',
	'Northwood Station',
	'Northwood Hills Station',
	'Notting Hill Gate Station',
	'Oakwood Station',
	'Old Street Station',
	'Osterley Station',
	'Oval Station',
	'Oxford Circus Station',
	'Paddington Station',
	'Park Royal Station',
	'Parsons Green Station',
	'Perivale Station',
	'Piccadilly Circus Station',
	'Pimlico Station',
	'Pinner Station',
	'Plaistow Station',
	'Preston Road Station',
	'Putney Bridge Station',
	'Queensbury Station',
	'Queensway Station',
	'Ravenscourt Park Station',
	'Rayners Lane Station',
	'Redbridge Station',
	"Regent's Park Station",
	'Rickmansworth Station',
	'Roding Valley Station',
	'Rotherhithe Station',
	'Royal Oak Station',
	'Ruislip Station',
	'Ruislip Gardens Station',
	'Ruislip Manor Station',
	'Russell Square Station',
	'Seven Sisters Station',
	'Shadwell Station',
	'Sloane Square Station',
	'Snaresbrook Station',
	'South Ealing Station',
	'South Harrow Station',
	'South Kensington Station',
	'South Ruislip Station',
	'South Wimbledon Station',
	'South Woodford Station',
	'Southfields Station',
	'Southgate Station',
	'Southwark Station',
	'Stamford Brook Station',
	'Stanmore Station',
	'Stepney Green Station',
	'Stockwell Station',
	'Stratford Station',
	'Sudbury Hill Station',
	'Sudbury Town Station',
	'Surrey Quays Station',
	'Swiss Cottage Station',
	'Temple Station',
	'Theydon Bois Station',
	'Tooting Bec Station',
	'Tooting Broadway Station',
	'Tottenham Court Road Station',
	'Tottenham Hale Station',
	'Totteridge & Whetstone Station',
	'Tower Hill Station',
	'Tufnell Park Station',
	'Turnham Green Station',
	'Turnpike Lane Station',
	'Upminster Station',
	'Upminster Bridge Station',
	'Upney Station',
	'Upton Park Station',
	'Uxbridge Station',
	'Vauxhall Station',
	'Victoria Station',
	'Walthamstow Central Station',
	'Wanstead Station',
	'Wapping Station',
	'Warren Street Station',
	'Warwick Avenue Station',
	'Waterloo Station',
	'Watford Station',
	'Wembley Park Station',
	'West Acton Station',
	'West Brompton Station',
	'West Finchley Station',
	'West Ham Station',
	'West Hampstead Station',
	'West Harrow Station',
	'West Kensington Station',
	'West Ruislip Station',
	'Westbourne Park Station',
	'Westminster Station',
	'White City Station',
	'Whitechapel Station',
	'Willesden Green Station',
	'Wimbledon Park Station',
	'Wood Green Station',
	'Woodford Station',
	'Woodside Park Station',
	'All Saints Station',
	'Beckton Station',
	'Beckton Park Station',
	'Blackwall Station',
	'Bow Church Station',
	'Bromley-By-Bow Station',
	'Crossharbour & London Arena Station',
	'Custom House Station',
	'Cutty Sark Station',
	'Cyprus Station',
	'Deptford Bridge Station',
	'Devons Road Station',
	'East India Station',
	'Edgware Road Bakerloo Station',
	'Edgware Road Circle Station',
	'Elverson Road Station',
	'Gallions Reach Station',
	'Greenwich Station',
	'Gunnersbury Station',
	'Hammersmith Station',
	'Hammersmith (D & P) Station',
	'Harlesden Station',
	'Harrow Wealdstone Station',
	'Harrow on the Hill Station',
	'Heathrow Terminals 1, 2, 3 Station',
	'Heron Quays Station',
	'Island Gardens Station',
	'Kensal Green Station',
	'Kensington (Olympia) Station',
	'Kenton Station',
	'Kew Gardens Station',
	"King's Cross St. Pancras Station",
	'Lewisham Station',
	'Limehouse Station',
	'Mudchute Station',
	'New Cross Station',
	'New Cross Gate Station',
	'North Wembley Station',
	'Poplar Station',
	'Prince Regent Station',
	'Pudding Mill Lane Station',
	"Queen's Park Station",
	'Richmond Station',
	'Royal Albert Station',
	'Royal Victoria Station',
	"Shepherd's Bush Central Station",
	"Shepherd's Bush Hammersmith & City Station",
	'South Kenton Station',
	'South Quay Station',
	'Shoreditch High Street',
	"St. James's Park Station",
	"St. John's Wood Station",
	"St. Paul's Station",
	'Stonebridge Park Station',
	'Tower Gateway Station',
	'Wembley Central Station',
	'West India Quay Station',
	'Westferry Station',
	'Willesden Junction Station',
	'Wimbledon Station'
];
